### ISSUE TITLE
Update Profile - Support Name Change

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#103]
1) not sure what we agreed on during the call… but the idea is having a top right button “edit” and make all the fields “editable”. If you have better solutions, ok for the better solutions.

https://xd.adobe.com/view/6601d8a5-a110-4331-bb6a-40d4e9c7786f-3352/
<img width="615" alt="image" src="https://user-images.githubusercontent.com/75991832/230190137-6814b541-5bd1-4d57-aea5-aaaa40fe7458.png">

**Comment by gguijarro-c-chwy** [comment]
NOT MVP. 

We have edit image and BIO working. This will be to support  name and it will be after MVP
