### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#11]
Summary:
As a Hypha Wallet user I want to be able to change the settings for the app.

AC:

- [x] Dark Mode
- [x] Secure Login
- [x] Backup 12 Words
- [x] Logout

Designs:
Dev Specs
Settings all screens (there is also Currencies, for the future)
https://xd.adobe.com/view/00e1dd45-e90a-439e-a847-6e4887685bfb-55b2/

Animation Prototype
Scroll > top and bottom navigation animations
https://xd.adobe.com/view/ef4be3bf-371a-49da-89da-8fca4230fa70-ba18/

Animation Prototype
“Indentation” > sub-pages, like “set currency button” > “currency list”
https://xd.adobe.com/view/5de18c15-9474-4fa8-ad1f-4c6133f94784-08b2/

**Comment by leonieherma1** [comment]
@luigicarlini1988 we need a logout button here

**Comment by luigicarlini1988** [comment]
@leonieherma1 added, and also a modal-bottom sheet "are you sure?" once you click it (need copy review)

**Comment by leonieherma1** [comment]
@gguijarro-c-chwy 

![Image](https://user-images.githubusercontent.com/75991832/214317022-37744036-d44f-427b-a0d7-b803251a3383.png)

**Comment by leonieherma1** [comment]
https://xd.adobe.com/view/00e1dd45-e90a-439e-a847-6e4887685bfb-55b2/
