### ISSUE TITLE
Swirl for waiting animation looks squashed

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#116]
**Describe the bug**
Minor graphics glitch

**To Reproduce**
1. Click scan
2. Wait for transaction

**Current behavior**
Waiting swirl gets squished along with the view port. 

**Expected behavior**
There's a round "waiting.." swirl

**Screenshots**
![IMG_51C1ACB71D34-1](https://user-images.githubusercontent.com/65412/231071050-79c91ae1-e296-4457-b585-e4b6b1671b25.jpeg)

https://user-images.githubusercontent.com/65412/231070480-1ca09f0d-7d1a-4b0a-8339-2b46e7b4e870.MOV

**Comment by gguijarro-c-chwy** [comment]
the is an issue with the can icon. Talking to luigi to get a new one

**Comment by gguijarro-c-chwy** [comment]
Fixed
