### ISSUE TITLE
Colour of top navigation (time, battery, etc...)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#120]
Reproduce: 
1. Open the app
2. Check navigation

Experienced behaviour:
First time i open the app the icons and font was black on black. then i went to another screen it changed to white on black (correct).

Expected behaviour:
Colour should be white on black 

<img width="279" alt="image" src="https://user-images.githubusercontent.com/75991832/231833421-5058fce9-4248-48cf-8548-96ed46ae4536.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/75991832/231833372-83154332-6673-40d4-ae9a-dd4bc9b77254.png">

**Comment by n13** [comment]
Unable to reproduce this - @gguijarro-c-chwy is this done?
