### ISSUE TITLE
Profile Screen: First action taking too long

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#124]
I think we will put the "first action taking too long" as an issue on the backlog. 

I know the reason, it's because we don't automatically "log in" to the ppp service, so we do it on whatever action needs it  when we're not logged in. It takes forever because it's making so many chain calls to sign the login transaction - 7 or so.

We can do it in the background

Reference: https://discord.com/channels/722537361480613950/1095806369187250256/1096067961174884462

**Comment by n13** [comment]
We could try to login on initial and disable the buttons while we are logging in....

**Comment by n13** [comment]
A little worried about race conditions, e.g. we are in the middle of login, then someone changes the picture.

**Comment by n13** [comment]
This is old, closing
