### ISSUE TITLE
Can't sign HUSD redemptioin

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#125]
Reproduce:
1. Go into dao.hypha.earth
2. Click on Login with Anchor
3. Login with Hypha Wallet
4. Go to /wallet or /profile 
5. Enter amount in "HUSD" field
6. Click "Redeem HUSD"

Expected behaviour:
I can sign the transaction in the Hypha Wallet to redeem HUSD

Experienced behaviour:
The transaction screen on the wallet is an empty white bottom sheet

<img width="301" alt="image" src="https://user-images.githubusercontent.com/75991832/232075201-68c4d81e-4047-40a1-86af-26cc4ab0b424.png">

**Comment by n13** [comment]
Fixed in build 13 

This PR fixed it: https://github.com/hypha-dao/hypha_wallet/pull/127
