### ISSUE TITLE
Logout is not working

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#132]
Reproduce:
1. Login with Hypha Wallet to [dao.hypha.earth/hypha](https://dao.hypha.earth/hypha/login)
2. Click "Logout" in the sidebar
3. Click "Login" on the login page

Expected behaviour:
I expect to be logged out and having to login in when I want to access the DAO again

Experienced behaviour:
I got logged out and when I click "login" again I am logged in to the DAO without having to sign a transaction.

Note:
- Also happens with SEEDS Light Wallet
- Does not happen with Anchor
- After refreshing the page, I am logged out

**Comment by n13** [comment]
Old
