### ISSUE TITLE
Invalid QR code causes endless spinner

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#199]
**Describe the bug**
Invalid QR code breaks scanner

**To Reproduce**
1. scan QR Code below (it is an invalid code)

**Current behavior**
Endless spinner

**Expected behavior**
Error snackbar, scanner remains functional and can scan valid codes

**Screenshots**
<img width="660" alt="image" src="https://github.com/hypha-dao/hypha_wallet/assets/65412/426fb6d9-9213-4e4e-b89e-c670cd741c53">

**Additional context**
I created this esr code when testing different sizes - stil, the wallet should never crash no matter how bad the code is..

**Comment by gguijarro-c-chwy** [comment]
https://github.com/hypha-dao/hypha_wallet/pull/200

**Comment by n13** [comment]
Fixed
