### ISSUE TITLE
Profile Service Library Flutter Integration

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#22]
Profile service is used for the following (MVP)

- [x] Set real name for account name
- [x] Set profile image for account name
- [x] Get real name for account name
- [x] Get profile image for account name

**Comment by n13** [comment]
Requirements: 

Onboard into profile with EOS username + image + name 

Edit profile (image, name, bio)

Get profile (image,name, organizations, bio)
