### ISSUE TITLE
Account creator service (backend)

### ISSUE THREAD

**Issue by gguijarro-c-chwy** [hypha-dao/hypha_wallet#35]
AC:
Have an account creation service running

**Comment by n13** [comment]
New architecture is 2 services running on the same server

- Account Creator
1. Accepts hashed secret from same server, or on a request with a secret key (protected). Stores hashed secrets. 
2. createAccount/ endpoint accepts a secret, public key, account name, chain. 
Hashes secret and looks up the hash - if it has an entry, this entry is removed and the account gets created.
Creates account
returns transactionID or error
