### ISSUE TITLE
Pull To Refresh on profile page

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#36]
**Is your feature request related to a problem? Please describe.**
Profile page loads profile data. 

It should have pull to refresh. 

**Describe the solution you'd like**
Pull to refresh loads profile data again. 

**Additional context**
Same event as init - just load data.

**Comment by gguijarro-c-chwy** [comment]
https://github.com/hypha-dao/hypha_wallet/pull/38
