### ISSUE TITLE
Pasting of 12 Word Seed Phrase not working

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#44]
**Summary**
As a Hypha Wallet user I would like to be able to copy paste my seed phrase from different formats so I can easily import my account into the app. 

AC:
Formatting we should support is:
- [x] breaks / return
- [ ] numbered list
- [x] comma
- [x] semi colom
- [ ] bullet list
- [ ] ?

**Comment by gguijarro-c-chwy** [comment]
Numbered and bullet list aint happening :P
