### ISSUE TITLE
Map contract actions to understandable words

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#48]
Summary:
As a Hypha Wallet user I would like to be able to understand the transactions that I am signing so I can make sure I only sign safe transactions.

AC:
Map all DAO transactions to understandable terms:

dao.hyhpa - cmntadd = Add a comment
dao.hypha - reactadd = Like a comment
dao.hypha - vote = Vote on a proposal
dao.hypha - propose = Publish your proposal to Staging
dao.hypha - proposepub = Publish your proposal on chain
dao.hypha - proposerem = Delete your proposal
husd.hypha - transfer = Redeem Cash Token

If we do not have the action mapped with a translation we show the original

**Comment by gguijarro-c-chwy** [comment]
hyhpa ???????? ..... @leonieherma1
