### ISSUE TITLE
Profile with no name or empty string username

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#51]
**Describe the bug**
There are two avatar image classes that, when there is no image, show initials. 

They both crash when username is either null or the empty string.

**To Reproduce**
1. Import account "testingseeds"
2. Observe crashes

**Current behavior**
App crashing

**Expected behavior**
Wherever the user image is showing, have an initial for testingseeds - could be TE, or T, or TS - doesn't really matter. 

As long as it's not crashing and showing something. I guess TE would make the most sense, although account names can in theory be 1 character long, I think. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by n13** [comment]
I tried to fix this but there's too many references all over the place and in generated classes, IDK how these can be fixed.

**Comment by gguijarro-c-chwy** [comment]
https://github.com/hypha-dao/hypha_wallet/pull/58
