### ISSUE TITLE
Signing via push notifications

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/hypha_wallet#57]
Summary:
As a Wallet user I would like to be able to sign all queued transactions automatically without having to scan the QR code again and again and again.

AC:

- [ ] frontend
- [ ] backend
- [ ] show push notifications

**Comment by n13** [comment]
We can actually implement this with push notifications.

**Comment by n13** [comment]
We might need to register device IDs on firebase

Then we can send PNs straight to user devices.
