### ISSUE TITLE
Scan all chains on import

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#65]
**Is your feature request related to a problem? Please describe.**

We need to support multiple chains and multiple accounts

**Describe the solution you'd like**
Just like anchor - when we import an account we scan all chains we know of looking for the public key

Show a list of all accounts on all chains with the key.

**Additional context**

**Comment by leonieherma1** [comment]
We are currently running this for Telos and we need to run it for EOS. The use case already supports the chain, we need to run it in parallel for both chains and return both results.

**Comment by leonieherma1** [comment]
Store network together with account name

**Comment by leonieherma1** [comment]
If no network is set, assume it is telos

**Comment by leonieherma1** [comment]
We also need to save the public key with the account name and the network
