### ISSUE TITLE
Handle Multiple Accounts

### ISSUE THREAD

**Issue by n13** [hypha-dao/hypha_wallet#66]
**Is your feature request related to a problem? Please describe.**
We need to be able to add accounts

**Describe the solution you'd like**
In settings, have a setting "Accounts" showing all accounts

Allow users to delete an account

Allow user to add an account

Add account leads to the same screens as the initial "import account" screens. Asks for phrase or private key, goes from there.

**Additional context**

**Comment by gguijarro-c-chwy** [comment]
Is this for MVP? @n13

**Comment by n13** [comment]
Priority of this feature:

There will not be that many users having more than 1 account

For those that do have more than 1 account, logging out and logging back in is really a very bad experience

We could do a simple implementation that remembers accounts and allows switching between them - that's logout/login

Or we could be fancy and just keep all accounts active all times, show a popup which account to sign with when someone has 2 accounts on 1 chain, etc.
